/**
 * Builds the fixture catalog every test resolves against (spec §7: everything must be
 * testable offline).
 *
 * The catalog is a plain skills repo — skills at `skills/<namespace>/<name>/SKILL.md`, MCP
 * entities at `mcps/<name>.yml`, a `scopes.yml` registry at the root — so it doubles as the
 * subject of the dotagents compatibility test (A26).
 *
 * It also builds that same catalog as a **local bare git repository**, which is how the git-source
 * tests stay offline: a `file://` URL is a git URL like any other, so nothing in ambit needs a test
 * mode to be exercised against one.
 *
 * Tests call `buildFixtureCatalog()`. To eyeball the fixture, `npm run fixture -- <dir>` runs
 * it directly — that path needs a Node with type stripping (22.18+ or 24+), unlike the
 * published CLI.
 */
import { execFile } from "node:child_process";
import { mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

/**
 * Written at the catalog root so a rebuild knows the directory is ours to delete. Dotfiles
 * are invisible to catalog parsing, which reads only `scopes.yml`, `skills/**`, and `mcps/*`.
 */
export const FIXTURE_MARKER = ".ambit-fixture";

const SCOPES_YML = `# The catalog's scope registry (spec §3.4). Every scope a skill or MCP declares must be
# registered here, so a typo fails loudly instead of silently matching nothing.
scopes:
  core:
    description: The universal floor — context everyone needs
  function.engineering:
    description: Building and shipping software
  function.engineering.frontend:
    description: "Browser-side work: components, styling, accessibility"
  project.acme:
    description: The Acme engagement
`;

const CORE_SKILL = `---
name: acme.commons.use-company-context
description: Canonical context about Acme — what it sells, to whom, and how it works.
ambit:
  scopes: [core]
---

# Acme company context

Selected by the \`core\` scope, and pulled in by \`requires\` from the project skill even when
\`core\` is not held.
`;

const ENGINEERING_SKILL = `---
name: acme.engineering.use-code-review
description: How Acme reviews code — what reviewers look for, and in what order.
ambit:
  scopes: [function.engineering]
---

# Code review at Acme

Selected by \`function.engineering\`, exactly. Holding \`core\` must not reach it.
`;

const FRONTEND_SKILL = `---
name: acme.engineering.frontend.use-design-tokens
description: Acme's design tokens — color, spacing, and the type scale.
ambit:
  scopes: [function.engineering.frontend]
  env: [ACME_FIGMA_TOKEN]
---

# Design tokens

Nested one level below \`function.engineering\`, so holding the parent selects it and holding
this scope does not reach back up.
`;

const PROJECT_SKILL = `---
name: acme.projects.use-acme-brief
description: The Acme engagement brief — scope, contacts, and conventions.
ambit:
  scopes: [project.acme]
  requires:
    - acme.commons.use-company-context
    - mcp.fixture
---

# Acme engagement brief

Reaches a skill and an MCP server that neither match by scope, so the \`requires\` closure is
the only thing that can pull them in.
`;

const REQUIRED_MCP = `name: fixture
# No scopes: reachable only because acme.projects.use-acme-brief requires it (spec §3.3).

transport:
  stdio:
    command: npx
    args: ["-y", "@acme/fixture-mcp"]

env: [FIXTURE_API_KEY]
`;

const SCOPED_MCP = `name: scoped
scopes: [function.engineering]

transport:
  http:
    url: https://mcp.invalid/fixture
    headers:
      Authorization: "Bearer \${SCOPED_API_KEY}"

env: [SCOPED_API_KEY]
`;

/** Every file in the fixture, keyed by its path relative to the catalog root. */
export const FIXTURE_CATALOG_FILES: Readonly<Record<string, string>> = {
  [FIXTURE_MARKER]: "generated by scripts/fixture-catalog.ts — safe to delete\n",
  "scopes.yml": SCOPES_YML,
  "mcps/fixture.yml": REQUIRED_MCP,
  "mcps/scoped.yml": SCOPED_MCP,
  "skills/acme/commons/use-company-context/SKILL.md": CORE_SKILL,
  "skills/acme/engineering/use-code-review/SKILL.md": ENGINEERING_SKILL,
  "skills/acme/engineering/frontend/use-design-tokens/SKILL.md": FRONTEND_SKILL,
  "skills/acme/projects/use-acme-brief/SKILL.md": PROJECT_SKILL,
};

async function isEmptyDirectory(dir: string): Promise<boolean> {
  return (await readdir(dir)).length === 0;
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

/**
 * Clears the target so a rebuild cannot leave stale files behind, refusing any directory the
 * builder did not create.
 */
async function clearTarget(dir: string): Promise<void> {
  if (!(await pathExists(dir))) return;

  const info = await stat(dir);
  if (!info.isDirectory()) {
    throw new Error(`fixture target is not a directory: ${dir}`);
  }
  if (!(await isEmptyDirectory(dir)) && !(await pathExists(path.join(dir, FIXTURE_MARKER)))) {
    throw new Error(
      `refusing to overwrite ${dir}: it is not empty and has no ${FIXTURE_MARKER} marker`,
    );
  }

  await rm(dir, { recursive: true, force: true });
}

/**
 * Writes the fixture catalog into `dir`, replacing any previous build. Idempotent: the same
 * `dir` always ends up with byte-identical contents and nothing extra.
 *
 * @returns the catalog root, absolute.
 */
export async function buildFixtureCatalog(dir: string): Promise<string> {
  const root = path.resolve(dir);
  await clearTarget(root);

  const files = Object.entries(FIXTURE_CATALOG_FILES).sort(([a], [b]) => (a < b ? -1 : 1));
  for (const [relative, contents] of files) {
    const target = path.join(root, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, contents, "utf8");
  }

  return root;
}

/** The branch the fixture repository's `HEAD` points at, so an absent `ref` finds something. */
export const FIXTURE_GIT_BRANCH = "main";

/** A tag on the same commit, so a test can ask for a ref that is not a branch. */
export const FIXTURE_GIT_TAG = "v1";

/** The bare repository, within the directory the builder is given. */
const BARE_DIRNAME = "catalog.git";

/** The working tree the bare repository is cloned from. */
const WORK_DIRNAME = "catalog-work";

/**
 * Fixed identity and dates, and neither user nor system config, so the fixture's commit SHA is the
 * same in every run on every machine — which is what lets a test name the cache path it produces.
 */
const FIXTURE_GIT_ENV: Readonly<Record<string, string>> = {
  GIT_CONFIG_NOSYSTEM: "1",
  GIT_CONFIG_GLOBAL: "/dev/null",
  GIT_AUTHOR_NAME: "ambit fixtures",
  GIT_AUTHOR_EMAIL: "fixtures@ambit.invalid",
  GIT_AUTHOR_DATE: "2024-01-01T00:00:00+00:00",
  GIT_COMMITTER_NAME: "ambit fixtures",
  GIT_COMMITTER_EMAIL: "fixtures@ambit.invalid",
  GIT_COMMITTER_DATE: "2024-01-01T00:00:00+00:00",
};

/** The fixture catalog as a git repository ambit can fetch without a network (spec §7). */
export interface FixtureGitCatalog {
  /** Absolute path to the bare repository. */
  readonly repo: string;
  /** A `file://` URL for it — a git URL like any other, so no test mode is needed. */
  readonly url: string;
  /** The commit both the branch and the tag point at. */
  readonly commit: string;
  readonly branch: string;
  readonly tag: string;
}

const execFileAsync = promisify(execFile);

async function git(args: readonly string[], cwd: string): Promise<string> {
  const { stdout } = await execFileAsync("git", [...args], {
    cwd,
    env: { ...process.env, ...FIXTURE_GIT_ENV },
    encoding: "utf8",
  });
  return stdout.trim();
}

/**
 * Builds the fixture catalog as a bare git repository inside `dir`, replacing any previous build.
 *
 * The tree committed is exactly {@link buildFixtureCatalog}'s, so a git-source install and a
 * `path:`-source install of the same fixture must produce identical results — which is the claim the
 * git-source tests make.
 */
export async function buildFixtureGitCatalog(dir: string): Promise<FixtureGitCatalog> {
  const root = path.resolve(dir);
  const work = path.join(root, WORK_DIRNAME);
  const repo = path.join(root, BARE_DIRNAME);

  await rm(work, { recursive: true, force: true });
  await rm(repo, { recursive: true, force: true });
  await buildFixtureCatalog(work);

  await git(["init", "--quiet"], work);
  // `symbolic-ref` rather than `init -b`: it names the initial branch the same way to every git.
  await git(["symbolic-ref", "HEAD", `refs/heads/${FIXTURE_GIT_BRANCH}`], work);
  await git(["add", "--all"], work);
  await git(["commit", "--quiet", "--message", "the fixture catalog"], work);
  await git(["tag", FIXTURE_GIT_TAG], work);
  const commit = await git(["rev-parse", "HEAD"], work);

  await git(["clone", "--mirror", "--quiet", "--", work, repo], root);

  return { repo, url: `file://${repo}`, commit, branch: FIXTURE_GIT_BRANCH, tag: FIXTURE_GIT_TAG };
}

const DEFAULT_DIR = "test/tmp/fixture-catalog";

async function main(argv: readonly string[]): Promise<void> {
  const dir = argv[0] ?? DEFAULT_DIR;
  const root = await buildFixtureCatalog(dir);
  console.log(`fixture catalog written to ${root}`);
}

const entry = process.argv[1];
if (entry && path.resolve(entry) === fileURLToPath(import.meta.url)) {
  await main(process.argv.slice(2));
}
